services:
    guigui35_platform.antispam:
        class: guigui35\PlatformBundle\Antispam\guigui35Antispam
        arguments: [@mailer, %locale%, 50]
        
        
parameters:
    mon_parametre_de_test: 42
        
#        arguments: ["@service_id", "plain_value", %parameter%]
